/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SortingGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Config");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConfigAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cConfigKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Assignment cParamsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cParamsParamParserRuleCall_4_0 = (RuleCall)cParamsAssignment_4.eContents().get(0);
		private final Assignment cImportsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cImportsImportParserRuleCall_5_0 = (RuleCall)cImportsAssignment_5.eContents().get(0);
		private final Assignment cComponentsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cComponentsComponentParserRuleCall_6_0 = (RuleCall)cComponentsAssignment_6.eContents().get(0);
		private final Assignment cInstancesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cInstancesInstanceParserRuleCall_7_0 = (RuleCall)cInstancesAssignment_7.eContents().get(0);
		private final Assignment cTransitionsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTransitionsTransitionParserRuleCall_8_0 = (RuleCall)cTransitionsAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Config:
		//	{Config}
		//	'config' '{' name=ID
		//	params+=Param+
		//	imports+=Import+
		//	components+=Component+
		//	instances+=Instance+
		//	transitions+=Transition+ '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Config} 'config' '{' name=ID params+=Param+ imports+=Import+ components+=Component+ instances+=Instance+
		//transitions+=Transition+ '}'
		public Group getGroup() { return cGroup; }
		
		//{Config}
		public Action getConfigAction_0() { return cConfigAction_0; }
		
		//'config'
		public Keyword getConfigKeyword_1() { return cConfigKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//params+=Param+
		public Assignment getParamsAssignment_4() { return cParamsAssignment_4; }
		
		//Param
		public RuleCall getParamsParamParserRuleCall_4_0() { return cParamsParamParserRuleCall_4_0; }
		
		//imports+=Import+
		public Assignment getImportsAssignment_5() { return cImportsAssignment_5; }
		
		//Import
		public RuleCall getImportsImportParserRuleCall_5_0() { return cImportsImportParserRuleCall_5_0; }
		
		//components+=Component+
		public Assignment getComponentsAssignment_6() { return cComponentsAssignment_6; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_6_0() { return cComponentsComponentParserRuleCall_6_0; }
		
		//instances+=Instance+
		public Assignment getInstancesAssignment_7() { return cInstancesAssignment_7; }
		
		//Instance
		public RuleCall getInstancesInstanceParserRuleCall_7_0() { return cInstancesInstanceParserRuleCall_7_0; }
		
		//transitions+=Transition+
		public Assignment getTransitionsAssignment_8() { return cTransitionsAssignment_8; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_8_0() { return cTransitionsTransitionParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Param");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameCommercialAtKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cIntvalAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cIntvalINTTerminalRuleCall_2_0_0 = (RuleCall)cIntvalAssignment_2_0.eContents().get(0);
		private final Assignment cStringvalAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cStringvalSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cStringvalAssignment_2_1.eContents().get(0);
		
		//Param:
		//	name='@' '=' (intval=INT | stringval=STRING);
		@Override public ParserRule getRule() { return rule; }
		
		//name='@' '=' (intval=INT | stringval=STRING)
		public Group getGroup() { return cGroup; }
		
		//name='@'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'@'
		public Keyword getNameCommercialAtKeyword_0_0() { return cNameCommercialAtKeyword_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//intval=INT | stringval=STRING
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//intval=INT
		public Assignment getIntvalAssignment_2_0() { return cIntvalAssignment_2_0; }
		
		//INT
		public RuleCall getIntvalINTTerminalRuleCall_2_0_0() { return cIntvalINTTerminalRuleCall_2_0_0; }
		
		//stringval=STRING
		public Assignment getStringvalAssignment_2_1() { return cStringvalAssignment_2_1; }
		
		//STRING
		public RuleCall getStringvalSTRINGTerminalRuleCall_2_1_0() { return cStringvalSTRINGTerminalRuleCall_2_1_0; }
	}
	public class QualifiedNameWithWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.QualifiedNameWithWildcard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildcard:
		//	QualifiedName '.*'?;
		@Override public ParserRule getRule() { return rule; }
		
		//QualifiedName '.*'?
		public Group getGroup() { return cGroup; }
		
		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }
		
		//'.*'?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameWithWildcardParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Import:
		//	'import' name=QualifiedNameWithWildcard;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' name=QualifiedNameWithWildcard
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//name=QualifiedNameWithWildcard
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//QualifiedNameWithWildcard
		public RuleCall getNameQualifiedNameWithWildcardParserRuleCall_1_0() { return cNameQualifiedNameWithWildcardParserRuleCall_1_0; }
	}
	public class PortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Port");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		
		//Port:
		//	name=ID type=Type;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID type=Type
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//type=Type
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_1_0() { return cTypeTypeParserRuleCall_1_0; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Type");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cTypeAlternatives_0_0 = (Alternatives)cTypeAssignment_0.eContents().get(0);
		private final Keyword cTypeIntKeyword_0_0_0 = (Keyword)cTypeAlternatives_0_0.eContents().get(0);
		private final Keyword cTypeStringKeyword_0_0_1 = (Keyword)cTypeAlternatives_0_0.eContents().get(1);
		private final Keyword cTypeDoubleKeyword_0_0_2 = (Keyword)cTypeAlternatives_0_0.eContents().get(2);
		private final Keyword cTypeLongKeyword_0_0_3 = (Keyword)cTypeAlternatives_0_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//Type:
		//	type=('int' | 'String' | 'double' | 'long') ('[' ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//type=('int' | 'String' | 'double' | 'long') ('[' ']')?
		public Group getGroup() { return cGroup; }
		
		//type=('int' | 'String' | 'double' | 'long')
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//('int' | 'String' | 'double' | 'long')
		public Alternatives getTypeAlternatives_0_0() { return cTypeAlternatives_0_0; }
		
		//'int'
		public Keyword getTypeIntKeyword_0_0_0() { return cTypeIntKeyword_0_0_0; }
		
		//'String'
		public Keyword getTypeStringKeyword_0_0_1() { return cTypeStringKeyword_0_0_1; }
		
		//'double'
		public Keyword getTypeDoubleKeyword_0_0_2() { return cTypeDoubleKeyword_0_0_2; }
		
		//'long'
		public Keyword getTypeLongKeyword_0_0_3() { return cTypeLongKeyword_0_0_3; }
		
		//('[' ']')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1_0() { return cLeftSquareBracketKeyword_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_1_1() { return cRightSquareBracketKeyword_1_1; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Component");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSourceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSinkParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFilterParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Component:
		//	Source | Sink | Filter;
		@Override public ParserRule getRule() { return rule; }
		
		//Source | Sink | Filter
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Source
		public RuleCall getSourceParserRuleCall_0() { return cSourceParserRuleCall_0; }
		
		//Sink
		public RuleCall getSinkParserRuleCall_1() { return cSinkParserRuleCall_1; }
		
		//Filter
		public RuleCall getFilterParserRuleCall_2() { return cFilterParserRuleCall_2; }
	}
	public class SourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Source");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cInKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cInPortsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cInPortsPortParserRuleCall_3_1_0 = (RuleCall)cInPortsAssignment_3_1.eContents().get(0);
		private final Keyword cOutKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cOutPortsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOutPortsPortParserRuleCall_5_0 = (RuleCall)cOutPortsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMethodKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMethodAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMethodSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cMethodAssignment_6_1.eContents().get(0);
		private final Group cGroup_6_2 = (Group)cGroup_6.eContents().get(2);
		private final Keyword cFullStopKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_6_2_1 = (RuleCall)cGroup_6_2.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Source:
		//	'source' name=ID '{' ('in:' inPorts+=Port+)?
		//	'out:' outPorts+=Port+ ('method:' method=STRING ('.' STRING)*)? //default and optional
		//	'}'
		//	//TODO foreach N (param ou unknown)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'source' name=ID '{' ('in:' inPorts+=Port+)? 'out:' outPorts+=Port+ ('method:' method=STRING ('.' STRING)*)? //default and optional
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'source'
		public Keyword getSourceKeyword_0() { return cSourceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('in:' inPorts+=Port+)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'in:'
		public Keyword getInKeyword_3_0() { return cInKeyword_3_0; }
		
		//inPorts+=Port+
		public Assignment getInPortsAssignment_3_1() { return cInPortsAssignment_3_1; }
		
		//Port
		public RuleCall getInPortsPortParserRuleCall_3_1_0() { return cInPortsPortParserRuleCall_3_1_0; }
		
		//'out:'
		public Keyword getOutKeyword_4() { return cOutKeyword_4; }
		
		//outPorts+=Port+
		public Assignment getOutPortsAssignment_5() { return cOutPortsAssignment_5; }
		
		//Port
		public RuleCall getOutPortsPortParserRuleCall_5_0() { return cOutPortsPortParserRuleCall_5_0; }
		
		//('method:' method=STRING ('.' STRING)*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'method:'
		public Keyword getMethodKeyword_6_0() { return cMethodKeyword_6_0; }
		
		//method=STRING
		public Assignment getMethodAssignment_6_1() { return cMethodAssignment_6_1; }
		
		//STRING
		public RuleCall getMethodSTRINGTerminalRuleCall_6_1_0() { return cMethodSTRINGTerminalRuleCall_6_1_0; }
		
		//('.' STRING)*
		public Group getGroup_6_2() { return cGroup_6_2; }
		
		//'.'
		public Keyword getFullStopKeyword_6_2_0() { return cFullStopKeyword_6_2_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_6_2_1() { return cSTRINGTerminalRuleCall_6_2_1; }
		
		////default and optional
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class FilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Filter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFilterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cInKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cInPortsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cInPortsPortParserRuleCall_4_0 = (RuleCall)cInPortsAssignment_4.eContents().get(0);
		private final Keyword cOutKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOutPortsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOutPortsPortParserRuleCall_6_0 = (RuleCall)cOutPortsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMethodKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMethodAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMethodSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cMethodAssignment_7_1.eContents().get(0);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cFullStopKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_7_2_1 = (RuleCall)cGroup_7_2.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Filter:
		//	'filter' name=ID '{'
		//	'in:' inPorts+=Port+
		//	'out:' outPorts+=Port+ ('method:' method=STRING ('.' STRING)*)? //default and optional
		//	//TODO adicionar codigo ao método
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'filter' name=ID '{' 'in:' inPorts+=Port+ 'out:' outPorts+=Port+ ('method:' method=STRING ('.' STRING)*)? //default and optional
		////TODO adicionar codigo ao método
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'filter'
		public Keyword getFilterKeyword_0() { return cFilterKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'in:'
		public Keyword getInKeyword_3() { return cInKeyword_3; }
		
		//inPorts+=Port+
		public Assignment getInPortsAssignment_4() { return cInPortsAssignment_4; }
		
		//Port
		public RuleCall getInPortsPortParserRuleCall_4_0() { return cInPortsPortParserRuleCall_4_0; }
		
		//'out:'
		public Keyword getOutKeyword_5() { return cOutKeyword_5; }
		
		//outPorts+=Port+
		public Assignment getOutPortsAssignment_6() { return cOutPortsAssignment_6; }
		
		//Port
		public RuleCall getOutPortsPortParserRuleCall_6_0() { return cOutPortsPortParserRuleCall_6_0; }
		
		//('method:' method=STRING ('.' STRING)*)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'method:'
		public Keyword getMethodKeyword_7_0() { return cMethodKeyword_7_0; }
		
		//method=STRING
		public Assignment getMethodAssignment_7_1() { return cMethodAssignment_7_1; }
		
		//STRING
		public RuleCall getMethodSTRINGTerminalRuleCall_7_1_0() { return cMethodSTRINGTerminalRuleCall_7_1_0; }
		
		//('.' STRING)*
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//'.'
		public Keyword getFullStopKeyword_7_2_0() { return cFullStopKeyword_7_2_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_7_2_1() { return cSTRINGTerminalRuleCall_7_2_1; }
		
		////default and optional
		////TODO adicionar codigo ao método
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class SinkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Sink");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSinkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cInKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cInPortsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cInPortsPortParserRuleCall_4_0 = (RuleCall)cInPortsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOutPortsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cOutPortsPortParserRuleCall_5_1_0 = (RuleCall)cOutPortsAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMethodKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMethodAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMethodSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cMethodAssignment_6_1.eContents().get(0);
		private final Group cGroup_6_2 = (Group)cGroup_6.eContents().get(2);
		private final Keyword cFullStopKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_6_2_1 = (RuleCall)cGroup_6_2.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Sink:
		//	'sink' name=ID '{'
		//	'in:' inPorts+=Port+ ('out:' outPorts+=Port+)? ('method:' method=STRING ('.' STRING)*)? //default and optional
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'sink' name=ID '{' 'in:' inPorts+=Port+ ('out:' outPorts+=Port+)? ('method:' method=STRING ('.' STRING)*)? //default and optional
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'sink'
		public Keyword getSinkKeyword_0() { return cSinkKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'in:'
		public Keyword getInKeyword_3() { return cInKeyword_3; }
		
		//inPorts+=Port+
		public Assignment getInPortsAssignment_4() { return cInPortsAssignment_4; }
		
		//Port
		public RuleCall getInPortsPortParserRuleCall_4_0() { return cInPortsPortParserRuleCall_4_0; }
		
		//('out:' outPorts+=Port+)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'out:'
		public Keyword getOutKeyword_5_0() { return cOutKeyword_5_0; }
		
		//outPorts+=Port+
		public Assignment getOutPortsAssignment_5_1() { return cOutPortsAssignment_5_1; }
		
		//Port
		public RuleCall getOutPortsPortParserRuleCall_5_1_0() { return cOutPortsPortParserRuleCall_5_1_0; }
		
		//('method:' method=STRING ('.' STRING)*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'method:'
		public Keyword getMethodKeyword_6_0() { return cMethodKeyword_6_0; }
		
		//method=STRING
		public Assignment getMethodAssignment_6_1() { return cMethodAssignment_6_1; }
		
		//STRING
		public RuleCall getMethodSTRINGTerminalRuleCall_6_1_0() { return cMethodSTRINGTerminalRuleCall_6_1_0; }
		
		//('.' STRING)*
		public Group getGroup_6_2() { return cGroup_6_2; }
		
		//'.'
		public Keyword getFullStopKeyword_6_2_0() { return cFullStopKeyword_6_2_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_6_2_1() { return cSTRINGTerminalRuleCall_6_2_1; }
		
		////default and optional
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class InstanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Instance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cComponentAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cComponentComponentCrossReference_0_0 = (CrossReference)cComponentAssignment_0.eContents().get(0);
		private final RuleCall cComponentComponentIDTerminalRuleCall_0_0_1 = (RuleCall)cComponentComponentCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Alternatives cAlternatives_2_1 = (Alternatives)cGroup_2.eContents().get(1);
		private final Group cGroup_2_1_0 = (Group)cAlternatives_2_1.eContents().get(0);
		private final Keyword cCallKeyword_2_1_0_0 = (Keyword)cGroup_2_1_0.eContents().get(0);
		private final Assignment cMethodAssignment_2_1_0_1 = (Assignment)cGroup_2_1_0.eContents().get(1);
		private final RuleCall cMethodSTRINGTerminalRuleCall_2_1_0_1_0 = (RuleCall)cMethodAssignment_2_1_0_1.eContents().get(0);
		private final Group cGroup_2_1_0_2 = (Group)cGroup_2_1_0.eContents().get(2);
		private final Keyword cFullStopKeyword_2_1_0_2_0 = (Keyword)cGroup_2_1_0_2.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_2_1_0_2_1 = (RuleCall)cGroup_2_1_0_2.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2_1_0_3 = (Keyword)cGroup_2_1_0.eContents().get(3);
		private final RuleCall cSTRINGTerminalRuleCall_2_1_0_4 = (RuleCall)cGroup_2_1_0.eContents().get(4);
		private final Group cGroup_2_1_0_5 = (Group)cGroup_2_1_0.eContents().get(5);
		private final Keyword cFullStopKeyword_2_1_0_5_0 = (Keyword)cGroup_2_1_0_5.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_2_1_0_5_1 = (RuleCall)cGroup_2_1_0_5.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2_1_0_6 = (Keyword)cGroup_2_1_0.eContents().get(6);
		private final Group cGroup_2_1_1 = (Group)cAlternatives_2_1.eContents().get(1);
		private final Keyword cArgsKeyword_2_1_1_0 = (Keyword)cGroup_2_1_1.eContents().get(0);
		private final Assignment cArgsAssignment_2_1_1_1 = (Assignment)cGroup_2_1_1.eContents().get(1);
		private final RuleCall cArgsSTRINGTerminalRuleCall_2_1_1_1_0 = (RuleCall)cArgsAssignment_2_1_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//Instance:
		//	component=[Component] name=ID ('{' ('call:' method=STRING ('.' STRING)* '(' STRING ('.' STRING)* ')' | 'args:'
		//	args+=STRING*) '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//component=[Component] name=ID ('{' ('call:' method=STRING ('.' STRING)* '(' STRING ('.' STRING)* ')' | 'args:'
		//args+=STRING*) '}')?
		public Group getGroup() { return cGroup; }
		
		//component=[Component]
		public Assignment getComponentAssignment_0() { return cComponentAssignment_0; }
		
		//[Component]
		public CrossReference getComponentComponentCrossReference_0_0() { return cComponentComponentCrossReference_0_0; }
		
		//ID
		public RuleCall getComponentComponentIDTerminalRuleCall_0_0_1() { return cComponentComponentIDTerminalRuleCall_0_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//('{' ('call:' method=STRING ('.' STRING)* '(' STRING ('.' STRING)* ')' | 'args:' args+=STRING*) '}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//'call:' method=STRING ('.' STRING)* '(' STRING ('.' STRING)* ')' | 'args:' args+=STRING*
		public Alternatives getAlternatives_2_1() { return cAlternatives_2_1; }
		
		//'call:' method=STRING ('.' STRING)* '(' STRING ('.' STRING)* ')'
		public Group getGroup_2_1_0() { return cGroup_2_1_0; }
		
		//'call:'
		public Keyword getCallKeyword_2_1_0_0() { return cCallKeyword_2_1_0_0; }
		
		//method=STRING
		public Assignment getMethodAssignment_2_1_0_1() { return cMethodAssignment_2_1_0_1; }
		
		//STRING
		public RuleCall getMethodSTRINGTerminalRuleCall_2_1_0_1_0() { return cMethodSTRINGTerminalRuleCall_2_1_0_1_0; }
		
		//('.' STRING)*
		public Group getGroup_2_1_0_2() { return cGroup_2_1_0_2; }
		
		//'.'
		public Keyword getFullStopKeyword_2_1_0_2_0() { return cFullStopKeyword_2_1_0_2_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2_1_0_2_1() { return cSTRINGTerminalRuleCall_2_1_0_2_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1_0_3() { return cLeftParenthesisKeyword_2_1_0_3; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2_1_0_4() { return cSTRINGTerminalRuleCall_2_1_0_4; }
		
		//('.' STRING)*
		public Group getGroup_2_1_0_5() { return cGroup_2_1_0_5; }
		
		//'.'
		public Keyword getFullStopKeyword_2_1_0_5_0() { return cFullStopKeyword_2_1_0_5_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2_1_0_5_1() { return cSTRINGTerminalRuleCall_2_1_0_5_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1_0_6() { return cRightParenthesisKeyword_2_1_0_6; }
		
		//'args:' args+=STRING*
		public Group getGroup_2_1_1() { return cGroup_2_1_1; }
		
		//'args:'
		public Keyword getArgsKeyword_2_1_1_0() { return cArgsKeyword_2_1_1_0; }
		
		//args+=STRING*
		public Assignment getArgsAssignment_2_1_1_1() { return cArgsAssignment_2_1_1_1; }
		
		//STRING
		public RuleCall getArgsSTRINGTerminalRuleCall_2_1_1_1_0() { return cArgsSTRINGTerminalRuleCall_2_1_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_2() { return cRightCurlyBracketKeyword_2_2; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.sorting.Sorting.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSourceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cSourceInstanceCrossReference_1_0 = (CrossReference)cSourceAssignment_1.eContents().get(0);
		private final RuleCall cSourceInstanceIDTerminalRuleCall_1_0_1 = (RuleCall)cSourceInstanceCrossReference_1_0.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTargetPortAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTargetPortPortCrossReference_3_0 = (CrossReference)cTargetPortAssignment_3.eContents().get(0);
		private final RuleCall cTargetPortPortIDTerminalRuleCall_3_0_1 = (RuleCall)cTargetPortPortCrossReference_3_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTargetAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cTargetInstanceCrossReference_7_0 = (CrossReference)cTargetAssignment_7.eContents().get(0);
		private final RuleCall cTargetInstanceIDTerminalRuleCall_7_0_1 = (RuleCall)cTargetInstanceCrossReference_7_0.eContents().get(1);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cSourcePortAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cSourcePortPortCrossReference_9_0 = (CrossReference)cSourcePortAssignment_9.eContents().get(0);
		private final RuleCall cSourcePortPortIDTerminalRuleCall_9_0_1 = (RuleCall)cSourcePortPortCrossReference_9_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Transition: //(source=[Source]|source=[Filter]) "=>" (target=[Filter]|target=[Sink])|
		////source=[Instance] "=>" target=[Instance] /*sem Instance no Component*/
		//	'[' source=[Instance] ',' targetPort=[Port] ']' '->' '[' target=[Instance] ',' sourcePort=[Port] ']';
		@Override public ParserRule getRule() { return rule; }
		
		////(source=[Source]|source=[Filter]) "=>" (target=[Filter]|target=[Sink])|
		////source=[Instance] "=>" target=[Instance] /*sem Instance no Component*/
		//'[' source=[Instance] ',' targetPort=[Port] ']' '->' '[' target=[Instance] ',' sourcePort=[Port] ']'
		public Group getGroup() { return cGroup; }
		
		////(source=[Source]|source=[Filter]) "=>" (target=[Filter]|target=[Sink])|
		////source=[Instance] "=>" target=[Instance] /*sem Instance no Component*/
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//source=[Instance]
		public Assignment getSourceAssignment_1() { return cSourceAssignment_1; }
		
		//[Instance]
		public CrossReference getSourceInstanceCrossReference_1_0() { return cSourceInstanceCrossReference_1_0; }
		
		//ID
		public RuleCall getSourceInstanceIDTerminalRuleCall_1_0_1() { return cSourceInstanceIDTerminalRuleCall_1_0_1; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//targetPort=[Port]
		public Assignment getTargetPortAssignment_3() { return cTargetPortAssignment_3; }
		
		//[Port]
		public CrossReference getTargetPortPortCrossReference_3_0() { return cTargetPortPortCrossReference_3_0; }
		
		//ID
		public RuleCall getTargetPortPortIDTerminalRuleCall_3_0_1() { return cTargetPortPortIDTerminalRuleCall_3_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_5() { return cHyphenMinusGreaterThanSignKeyword_5; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_6() { return cLeftSquareBracketKeyword_6; }
		
		//target=[Instance]
		public Assignment getTargetAssignment_7() { return cTargetAssignment_7; }
		
		//[Instance]
		public CrossReference getTargetInstanceCrossReference_7_0() { return cTargetInstanceCrossReference_7_0; }
		
		//ID
		public RuleCall getTargetInstanceIDTerminalRuleCall_7_0_1() { return cTargetInstanceIDTerminalRuleCall_7_0_1; }
		
		//','
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//sourcePort=[Port]
		public Assignment getSourcePortAssignment_9() { return cSourcePortAssignment_9; }
		
		//[Port]
		public CrossReference getSourcePortPortCrossReference_9_0() { return cSourcePortPortCrossReference_9_0; }
		
		//ID
		public RuleCall getSourcePortPortIDTerminalRuleCall_9_0_1() { return cSourcePortPortIDTerminalRuleCall_9_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
	}
	
	
	private final ConfigElements pConfig;
	private final ParamElements pParam;
	private final QualifiedNameWithWildcardElements pQualifiedNameWithWildcard;
	private final QualifiedNameElements pQualifiedName;
	private final ImportElements pImport;
	private final PortElements pPort;
	private final TypeElements pType;
	private final ComponentElements pComponent;
	private final SourceElements pSource;
	private final FilterElements pFilter;
	private final SinkElements pSink;
	private final InstanceElements pInstance;
	private final TransitionElements pTransition;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SortingGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pConfig = new ConfigElements();
		this.pParam = new ParamElements();
		this.pQualifiedNameWithWildcard = new QualifiedNameWithWildcardElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pImport = new ImportElements();
		this.pPort = new PortElements();
		this.pType = new TypeElements();
		this.pComponent = new ComponentElements();
		this.pSource = new SourceElements();
		this.pFilter = new FilterElements();
		this.pSink = new SinkElements();
		this.pInstance = new InstanceElements();
		this.pTransition = new TransitionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.sorting.Sorting".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Config:
	//	{Config}
	//	'config' '{' name=ID
	//	params+=Param+
	//	imports+=Import+
	//	components+=Component+
	//	instances+=Instance+
	//	transitions+=Transition+ '}';
	public ConfigElements getConfigAccess() {
		return pConfig;
	}
	
	public ParserRule getConfigRule() {
		return getConfigAccess().getRule();
	}
	
	//Param:
	//	name='@' '=' (intval=INT | stringval=STRING);
	public ParamElements getParamAccess() {
		return pParam;
	}
	
	public ParserRule getParamRule() {
		return getParamAccess().getRule();
	}
	
	//QualifiedNameWithWildcard:
	//	QualifiedName '.*'?;
	public QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return pQualifiedNameWithWildcard;
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//Import:
	//	'import' name=QualifiedNameWithWildcard;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}
	
	//Port:
	//	name=ID type=Type;
	public PortElements getPortAccess() {
		return pPort;
	}
	
	public ParserRule getPortRule() {
		return getPortAccess().getRule();
	}
	
	//Type:
	//	type=('int' | 'String' | 'double' | 'long') ('[' ']')?;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Component:
	//	Source | Sink | Filter;
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//Source:
	//	'source' name=ID '{' ('in:' inPorts+=Port+)?
	//	'out:' outPorts+=Port+ ('method:' method=STRING ('.' STRING)*)? //default and optional
	//	'}'
	//	//TODO foreach N (param ou unknown)
	//;
	public SourceElements getSourceAccess() {
		return pSource;
	}
	
	public ParserRule getSourceRule() {
		return getSourceAccess().getRule();
	}
	
	//Filter:
	//	'filter' name=ID '{'
	//	'in:' inPorts+=Port+
	//	'out:' outPorts+=Port+ ('method:' method=STRING ('.' STRING)*)? //default and optional
	//	//TODO adicionar codigo ao método
	//	'}';
	public FilterElements getFilterAccess() {
		return pFilter;
	}
	
	public ParserRule getFilterRule() {
		return getFilterAccess().getRule();
	}
	
	//Sink:
	//	'sink' name=ID '{'
	//	'in:' inPorts+=Port+ ('out:' outPorts+=Port+)? ('method:' method=STRING ('.' STRING)*)? //default and optional
	//	'}';
	public SinkElements getSinkAccess() {
		return pSink;
	}
	
	public ParserRule getSinkRule() {
		return getSinkAccess().getRule();
	}
	
	//Instance:
	//	component=[Component] name=ID ('{' ('call:' method=STRING ('.' STRING)* '(' STRING ('.' STRING)* ')' | 'args:'
	//	args+=STRING*) '}')?;
	public InstanceElements getInstanceAccess() {
		return pInstance;
	}
	
	public ParserRule getInstanceRule() {
		return getInstanceAccess().getRule();
	}
	
	//Transition: //(source=[Source]|source=[Filter]) "=>" (target=[Filter]|target=[Sink])|
	////source=[Instance] "=>" target=[Instance] /*sem Instance no Component*/
	//	'[' source=[Instance] ',' targetPort=[Port] ']' '->' '[' target=[Instance] ',' sourcePort=[Port] ']';
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
