/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting.sorting;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sorting.sorting.Param#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.sorting.sorting.Param#getIntval <em>Intval</em>}</li>
 *   <li>{@link org.xtext.example.sorting.sorting.Param#getStringval <em>Stringval</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sorting.sorting.SortingPackage#getParam()
 * @model
 * @generated
 */
public interface Param extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.sorting.sorting.SortingPackage#getParam_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.sorting.sorting.Param#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Intval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Intval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intval</em>' attribute.
   * @see #setIntval(int)
   * @see org.xtext.example.sorting.sorting.SortingPackage#getParam_Intval()
   * @model
   * @generated
   */
  int getIntval();

  /**
   * Sets the value of the '{@link org.xtext.example.sorting.sorting.Param#getIntval <em>Intval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Intval</em>' attribute.
   * @see #getIntval()
   * @generated
   */
  void setIntval(int value);

  /**
   * Returns the value of the '<em><b>Stringval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stringval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stringval</em>' attribute.
   * @see #setStringval(String)
   * @see org.xtext.example.sorting.sorting.SortingPackage#getParam_Stringval()
   * @model
   * @generated
   */
  String getStringval();

  /**
   * Sets the value of the '{@link org.xtext.example.sorting.sorting.Param#getStringval <em>Stringval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stringval</em>' attribute.
   * @see #getStringval()
   * @generated
   */
  void setStringval(String value);

} // Param
