/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting.sorting.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.sorting.sorting.Param;
import org.xtext.example.sorting.sorting.SortingPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Param</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sorting.sorting.impl.ParamImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.sorting.sorting.impl.ParamImpl#getIntval <em>Intval</em>}</li>
 *   <li>{@link org.xtext.example.sorting.sorting.impl.ParamImpl#getStringval <em>Stringval</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParamImpl extends MinimalEObjectImpl.Container implements Param
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getIntval() <em>Intval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntval()
   * @generated
   * @ordered
   */
  protected static final int INTVAL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIntval() <em>Intval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntval()
   * @generated
   * @ordered
   */
  protected int intval = INTVAL_EDEFAULT;

  /**
   * The default value of the '{@link #getStringval() <em>Stringval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringval()
   * @generated
   * @ordered
   */
  protected static final String STRINGVAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStringval() <em>Stringval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringval()
   * @generated
   * @ordered
   */
  protected String stringval = STRINGVAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParamImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SortingPackage.Literals.PARAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SortingPackage.PARAM__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getIntval()
  {
    return intval;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIntval(int newIntval)
  {
    int oldIntval = intval;
    intval = newIntval;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SortingPackage.PARAM__INTVAL, oldIntval, intval));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStringval()
  {
    return stringval;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStringval(String newStringval)
  {
    String oldStringval = stringval;
    stringval = newStringval;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SortingPackage.PARAM__STRINGVAL, oldStringval, stringval));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SortingPackage.PARAM__NAME:
        return getName();
      case SortingPackage.PARAM__INTVAL:
        return getIntval();
      case SortingPackage.PARAM__STRINGVAL:
        return getStringval();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SortingPackage.PARAM__NAME:
        setName((String)newValue);
        return;
      case SortingPackage.PARAM__INTVAL:
        setIntval((Integer)newValue);
        return;
      case SortingPackage.PARAM__STRINGVAL:
        setStringval((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SortingPackage.PARAM__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SortingPackage.PARAM__INTVAL:
        setIntval(INTVAL_EDEFAULT);
        return;
      case SortingPackage.PARAM__STRINGVAL:
        setStringval(STRINGVAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SortingPackage.PARAM__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SortingPackage.PARAM__INTVAL:
        return intval != INTVAL_EDEFAULT;
      case SortingPackage.PARAM__STRINGVAL:
        return STRINGVAL_EDEFAULT == null ? stringval != null : !STRINGVAL_EDEFAULT.equals(stringval);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", intval: ");
    result.append(intval);
    result.append(", stringval: ");
    result.append(stringval);
    result.append(')');
    return result.toString();
  }

} //ParamImpl
